services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=credit_postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A credit_system.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    working_dir: /app/credit_system
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  init:
    build: .
    depends_on:
      - db
      - redis
      - web
      - celery
    entrypoint: ["bash", "init.sh"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
